services:
  - type: web
    name: iotex-website
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
